# scripts/extract_ag_tracklet_features.py
"""
Extract tracklet-level features for the Air-Ground protocol generated by
`generate_simveri_release.py` (ag_protocol / ag_protocol_full).

Inputs (under --ag-root):
  - metadata/tracklets.json
  - images/air/*.jpg
  - images/ground/*.jpg

Outputs (under --output-dir):
  - tracklet_features.npy     (N, 2048) float32, L2-normalized
  - tracklet_index.json       list of tracklet records in the same order as .npy
  - features_meta.json        reproducibility metadata

Notes:
  - Uses the same FastReID-backed FeatureExtractor as the ground-ground pipeline.
  - Tracklet feature = mean(image_features) then L2-normalize.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import datetime
from typing import Dict, List

import numpy as np
from tqdm import tqdm


PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, PROJECT_ROOT)


def _load_json(path: str) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def _coerce_tracklets_dict(obj: object) -> Dict[str, dict]:
    """
    Support multiple tracklets.json formats:
      - dict: {tracklet_id: tracklet_dict}
      - list: [tracklet_dict, ...] (each has tracklet_id)
    """
    if isinstance(obj, dict):
        # Already a mapping; filter out any non-dict values defensively.
        return {k: v for k, v in obj.items() if isinstance(v, dict)}
    if isinstance(obj, list):
        out: Dict[str, dict] = {}
        for rec in obj:
            if not isinstance(rec, dict):
                continue
            tid = rec.get("tracklet_id")
            if isinstance(tid, str) and tid:
                out[tid] = rec
        return out
    return {}


def _load_tracklets_map(tracklets_path: str) -> tuple[Dict[str, dict], dict]:
    """
    Flatten the release-generated tracklets.json structure into {tracklet_id: tracklet_dict}.

    Newer releases store:
      {
        ...meta,
        "air_tracklets": {tid: {...}},
        "ground_tracklets": {tid: {...}}
      }
    """
    raw = _load_json(tracklets_path)
    if isinstance(raw, dict) and ("air_tracklets" in raw or "ground_tracklets" in raw):
        air = _coerce_tracklets_dict(raw.get("air_tracklets") or {})
        ground = _coerce_tracklets_dict(raw.get("ground_tracklets") or {})
        merged: Dict[str, dict] = {}
        merged.update(air)
        merged.update(ground)
        meta = {k: v for k, v in raw.items() if k not in ("air_tracklets", "ground_tracklets")}
        meta["air_tracklet_count"] = len(air)
        meta["ground_tracklet_count"] = len(ground)
        meta["tracklet_count"] = len(merged)
        return merged, meta

    # Legacy: already a flat mapping or list.
    flat = _coerce_tracklets_dict(raw)
    return flat, {"tracklet_count": len(flat)}


def _infer_layer(tracklet_id: str, tracklet: dict) -> str:
    layer = str(tracklet.get("layer", "")).lower().strip()
    if layer in ("air", "ground"):
        return layer
    if tracklet_id.startswith("air_"):
        return "air"
    return "ground"


def _image_path(ag_root: str, layer: str, image_name: str) -> str:
    return os.path.join(ag_root, "images", layer, image_name)


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Extract Air-Ground tracklet features")
    p.add_argument("--ag-root", type=str, required=True, help="Path to ag_protocol or ag_protocol_full folder")
    p.add_argument("--output-dir", type=str, required=True, help="Where to save extracted tracklet features")

    # Model / runtime
    p.add_argument("--model-path", type=str, default="", help="Path to model checkpoint (.pth)")
    p.add_argument("--use-veri", action="store_true", help="Use VeRi pretrained weights (if model-path not set)")
    p.add_argument("--device", type=str, default="cuda")
    p.add_argument("--input-size", type=int, default=256, help="Resize images to this square size before inference")

    # Performance
    p.add_argument("--max-images-per-tracklet", type=int, default=0, help="If >0, uniformly subsample to this many images per tracklet")
    return p.parse_args()


def _subsample_uniform(items: List[str], k: int) -> List[str]:
    if k <= 0 or len(items) <= k:
        return items
    idx = np.linspace(0, len(items) - 1, k, dtype=int)
    return [items[i] for i in idx]


def main() -> None:
    args = parse_args()
    ag_root = args.ag_root
    out_dir = args.output_dir
    os.makedirs(out_dir, exist_ok=True)

    tracklets_path = os.path.join(ag_root, "metadata", "tracklets.json")
    protocol_path = os.path.join(ag_root, "metadata", "protocol.json")
    if not os.path.exists(tracklets_path):
        raise FileNotFoundError(f"tracklets.json not found: {tracklets_path}")
    if not os.path.exists(protocol_path):
        raise FileNotFoundError(f"protocol.json not found: {protocol_path}")

    # Resolve model path
    veri_model_path = os.path.join(PROJECT_ROOT, "pretrained", "veri_sbs_R50-ibn.pth")
    if args.model_path:
        model_path = args.model_path
    elif args.use_veri and os.path.exists(veri_model_path):
        model_path = veri_model_path
    else:
        raise ValueError("Provide --model-path or use --use-veri (and ensure pretrained exists).")

    print("=" * 70)
    print("SimVeRi Air-Ground Tracklet Feature Extraction")
    print("=" * 70)
    print(f"Start time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"AG root:     {ag_root}")
    print(f"Model:       {model_path}")
    print(f"Input size:  {int(args.input_size)}")
    print(f"Output dir:  {out_dir}")

    from src.models.feature_extractor import FeatureExtractor

    tracklets, tracklets_meta = _load_tracklets_map(tracklets_path)
    tracklet_ids = sorted(tracklets.keys())
    if tracklets_meta.get("air_tracklet_count") is not None and tracklets_meta.get("ground_tracklet_count") is not None:
        print(
            f"Tracklets:   {len(tracklet_ids)} (air={tracklets_meta.get('air_tracklet_count')}, "
            f"ground={tracklets_meta.get('ground_tracklet_count')})"
        )
    else:
        print(f"Tracklets:   {len(tracklet_ids)}")

    extractor = FeatureExtractor(model_path=model_path, device=args.device, input_size=int(args.input_size))

    features = np.zeros((len(tracklet_ids), 2048), dtype=np.float32)
    index: List[dict] = []

    missing_images = 0

    for idx, tid in enumerate(tqdm(tracklet_ids, desc="Tracklets")):
        t = tracklets[tid]
        layer = _infer_layer(tid, t)
        images = list(t.get("images") or [])
        images = _subsample_uniform(images, int(args.max_images_per_tracklet))

        if not images:
            # Keep zeros, but record it.
            index.append(
                {
                    "tracklet_id": tid,
                    "layer": layer,
                    "camera_id": t.get("camera_id"),
                    "mapped_id": t.get("mapped_id"),
                    "image_count": 0,
                }
            )
            continue

        # Incremental mean to reduce memory.
        acc = np.zeros((2048,), dtype=np.float64)
        cnt = 0
        for name in images:
            p = _image_path(ag_root, layer, name)
            if not os.path.exists(p):
                missing_images += 1
                continue
            v = extractor.extract_single(p).astype(np.float64, copy=False)
            acc += v
            cnt += 1

        if cnt == 0:
            v = np.zeros((2048,), dtype=np.float32)
        else:
            v = (acc / float(cnt)).astype(np.float32)
            n = float(np.linalg.norm(v) + 1e-12)
            v = v / n

        features[idx] = v
        index.append(
            {
                "tracklet_id": tid,
                "layer": layer,
                "camera_id": t.get("camera_id"),
                "mapped_id": t.get("mapped_id"),
                "image_count": int(cnt),
            }
        )

    np.save(os.path.join(out_dir, "tracklet_features.npy"), features)
    with open(os.path.join(out_dir, "tracklet_index.json"), "w", encoding="utf-8") as f:
        json.dump(index, f, indent=2, ensure_ascii=False)

    meta = {
        "ag_root": os.path.abspath(ag_root),
        "model_path": os.path.abspath(model_path),
        "input_size": int(args.input_size),
        "tracklet_count": len(tracklet_ids),
        "generated_at": datetime.now().isoformat(),
        "missing_images": int(missing_images),
        "max_images_per_tracklet": int(args.max_images_per_tracklet),
    }
    with open(os.path.join(out_dir, "features_meta.json"), "w", encoding="utf-8") as f:
        json.dump(meta, f, indent=2, ensure_ascii=False)

    print("-" * 70)
    print("Done")
    print(f"Saved: {os.path.join(out_dir, 'tracklet_features.npy')}")
    print(f"Saved: {os.path.join(out_dir, 'tracklet_index.json')}")
    print(f"Saved: {os.path.join(out_dir, 'features_meta.json')}")
    if missing_images:
        print(f"Warning: missing_images={missing_images} (check AG copy step in release generation)")
    print("=" * 70)


if __name__ == "__main__":
    main()
